const JWT_TOKEN_GOT = 'TAKE_OUT_JWT_TOKEN'
const LOGIN = 'LOGIN'
const REGISTER = 'REGISTER'
const LOGINED = 'LOGINED'
const VISIT_COUNT_GOT = 'VISIT_COUNT_GOT'
const USER_NAME_GOT = 'USER_NAME_GOT'
const IMG_VIEWER_SHOW = 'IMG_VIEWER_SHOW'
const SEARCHED = 'SEARCHED'
const SEARCH_START = 'SEARCH_START'

const MERCARI_ITEM_GOT = 'MERCARI_ITEM_GOT'
const MERCARI_ITEM_GETTING = 'MERCARI_ITEM_GETTING'
const SEARCH_STASTIC_GOT = 'SEARCH_STASTIC_GOT'


export default {
  JWT_TOKEN_GOT,
  LOGIN,
  LOGINED,
  VISIT_COUNT_GOT,
  USER_NAME_GOT,
  IMG_VIEWER_SHOW,
  SEARCHED,
  MERCARI_ITEM_GOT,
  SEARCH_START,
  MERCARI_ITEM_GETTING,
  REGISTER,
  SEARCH_STASTIC_GOT,
}