const JWT_TOKEN_GOT = 'TAKE_OUT_JWT_TOKEN'
const LOGIN = 'LOGIN'
const LOGINED = 'LOGINED'
const VISIT_COUNT_GOT = 'VISIT_COUNT_GOT'
const USER_NAME_GOT = 'USER_NAME_GOT'
const IMG_VIEWER_SHOW = 'IMG_VIEWER_SHOW'
const SEARCHED = 'SEARCHED'

const SET_MERCARI_ITEM_ID = 'SET_MERCARI_ITEM_ID'


export default {
  JWT_TOKEN_GOT,
  LOGIN,
  LOGINED,
  VISIT_COUNT_GOT,
  USER_NAME_GOT,
  IMG_VIEWER_SHOW,
  SEARCHED,
  SET_MERCARI_ITEM_ID,
}